In [1]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [2]:
x,y=make_regression(n_samples=100,n_features=2,n_informative=2,n_targets=1,noise=50)

In [3]:
df=pd.DataFrame({'feature1':x[:,0],'feature2':x[:,1],'target':y})

In [4]:
df.head()

,feature1,feature2,target
0,-2.189640,-0.564286,-221.887963
1,-0.059707,-0.462965,8.279739
2,0.095751,-1.020453,-36.019831
3,0.840099,-0.042602,44.313998
4,1.142159,1.794588,215.425373


In [5]:
fig= px.scatter_3d(df,x='feature1',y='feature2',z='target')
fig.show()

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=3)

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
lr=LinearRegression()

In [10]:
lr.fit(x_train,y_train)

LinearRegression()

In [11]:
y_pred=lr.predict(x_test)

In [12]:
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("RMSE",np.sqrt(mean_squared_error(y_test,y_pred)))
print("R2 Score",r2_score(y_test,y_pred))

MAE 52.176456430012834
MSE 4181.806812885508
RMSE 64.66689116453263
R2 Score 0.7306448728940713


In [13]:
lr.coef_

array([101.4206132 ,  58.42946809])

In [14]:
lr.intercept_

np.float64(1.5827184169200805)

# **Self Made model for MLR**

In [15]:
from sklearn.datasets import load_diabetes

In [16]:
x,y=load_diabetes(return_X_y=True)

In [17]:
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [18]:
x.shape

(442, 10)

In [19]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=3)

In [22]:
x_train.shape

(353, 10)

In [23]:
x_test.shape

(89, 10)

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
lr=LinearRegression()

In [29]:
lr.fit(x_train,y_train)

LinearRegression()

In [30]:
y_pred=lr.predict(x_test)

In [31]:
r2_score(y_test,y_pred)

0.4161792211496943

In [32]:
lr.coef_

array([  -1.13744712, -212.8867836 ,  540.45536994,  345.20621542,
       -938.23814645,  516.62060367,  172.85885498,  267.87535242,
        732.63230159,   70.07849485])

In [33]:
lr.intercept_

np.float64(153.13441535285003)

In [50]:
# khud ka MLR ka code
class MeraMLR:
  def __init__(self):
    self.coef_=None
    self.intercept_=None

  def fit(self,x_train,y_train):
    x_train=np.insert(x_train,0,1,axis=1)
    betas=np.linalg.inv(np.dot(x_train.T,x_train)).dot(x_train.T).dot(y_train)
    self.intercept_=betas[0]
    self.coef_=betas[1:]

  def predict(self,x_test):
    y_pred=np.dot(x_test,self.coef_)+self.intercept_
    return y_pred

In [45]:
lr=MeraMLR()

In [46]:
lr.fit(x_train,y_train)

In [47]:
y_pred=lr.predict(x_test)

In [49]:
r2_score(y_test,y_pred)

0.4161792211496943